<a href="https://colab.research.google.com/github/sefahw/machine-learning-assignment/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
from keras.losses import CategoricalCrossentropy,MeanSquaredError,BinaryCrossentropy
from sklearn.preprocessing import OneHotEncoder
     

In [109]:
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28, 28)),tf.keras.layers.Dense(128,activation='relu'),tf.keras.layers.Dropout(0,2),tf.keras.layers.Dense(10)])
predictions=model(x_train[:1]).numpy()
predictions



array([[-0.9922015 ,  0.3579229 , -0.45579964,  0.27632618, -0.30271938,
         0.61458737, -0.6868111 ,  0.1838474 ,  0.3650565 , -0.949573  ]],
      dtype=float32)

In [110]:
tf.nn.softmax(predictions).numpy()

array([[0.0375508 , 0.14486745, 0.064206  , 0.13351615, 0.07482686,
        0.1872573 , 0.05096225, 0.12172247, 0.14590457, 0.03918615]],
      dtype=float32)

In [111]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True )

In [112]:
loss_fn(y_train[:1],predictions).numpy()

1.6752716

In [113]:
model.compile(optimizer='adam',loss=loss_fn, metrics=['accuracy'])

In [114]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2569 - accuracy: 0.9269
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1133 - accuracy: 0.9658
Epoch 3/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0790 - accuracy: 0.9761
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0587 - accuracy: 0.9822
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0460 - accuracy: 0.9861


In [115]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0809 - accuracy: 0.9739 - 713ms/epoch - 2ms/step


[0.08089426159858704, 0.9739000201225281]

In [116]:
#Load dataset
df = pd.read_csv("Iris.csv")
#Condition extraction from data frame
df = df[df["Species"]!="Iris-setosa"]
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
# NumPy 配列に変換
X = np.array(X)
y = np.array(y)
# Convert label to number
y[y == "Iris-versicolor"] = 0
y[y == "Iris-virginica"] = 1
y = y.astype(np.int64)[:, np.newaxis]

#Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train)
y_test_one_hot = enc.transform(y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [117]:
def classification_evaluation(x_train,y_train,x_test,crossentropy,verbose,output_units):
  model=Sequential()
  model.add(Dense(50,activation=tf.nn.relu))
  model.add(Dense(100,activation=tf.nn.relu))
  model.add(Dense(output_units,activation=tf.nn.sigmoid))
  model.compile(optimizer=Adam(learning_rate=0.001),loss=crossentropy(),metrics=["accuracy"])
  model.fit(x_train,y_train,shuffle=True,batch_size=10,epochs=300,verbose=verbose)
  score=model.evaluate(x_train,y_train,verbose=0)
  print('Train loss:', score[0])
  print('Train accuracy:',score[1])
  pred_proba=model.predict(x_test,batch_size=10)[:,0]
  rounded_preds=np.where(pred_proba> 0.5 , 1, 0)
  print(rounded_preds)

In [118]:
classification_evaluation(X_train,y_train,X_test,BinaryCrossentropy,0,1)

Train loss: 0.021126607432961464
Train accuracy: 1.0
2/2 [==============================] - 0s 4ms/step
[0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0]


In [119]:
#Load dataset
df = pd.read_csv("Iris.csv")
#Condition extraction from data frame
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
# NumPy 配列に変換
X = np.array(X)
y = np.array(y)
# Convert label to number
y[y == "Iris-setosa"] = 0
y[y == "Iris-versicolor"] = 1
y[y == "Iris-virginica"] = 2
y = y.astype(np.int64)[:, np.newaxis]

#Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
y_train_one_hot = enc.fit_transform(y_train)
y_test_one_hot = enc.transform(y_test)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [120]:
model = Sequential()
model.add(Dense(50, activation=tf.nn.relu))
model.add(Dense(100, activation=tf.nn.relu))
model.add(Dense(3, activation=tf.nn.softmax))
model.compile(optimizer=Adam(learning_rate=0.001), loss=CategoricalCrossentropy(), metrics=["accuracy"])
model.fit(X_train, y_train_one_hot, shuffle=True, batch_size=10, epochs=300, verbose=0)
score = model.evaluate(X_train, y_train_one_hot, verbose=0)
print('Train loss:', score[0])
print('Train accuracy:', score[1])
pred_proba = model.predict(X_test,batch_size=10)
pred = np.argmax(pred_proba, 1)
print(pred)

Train loss: 0.05960191413760185
Train accuracy: 0.9833333492279053
3/3 [==============================] - 0s 8ms/step
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


In [121]:
house_df=pd.read_csv("house_prices.csv")
house_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [122]:
h_x=house_df[['GrLivArea','YearBuilt']].to_numpy()
h_y=house_df['SalePrice'].to_numpy()

In [123]:
h_x.shape,h_y.shape

((1460, 2), (1460,))

In [124]:
h_x_train,h_x_test,h_y_train,h_y_test=train_test_split(h_x,h_y,train_size=0.2,random_state=0)

In [125]:
model=Sequential()
model.add(Dense(50,activation=tf.nn.relu))
model.add(Dense(100,activation=tf.nn.relu))
model.add(Dense(1,activation=tf.keras.activations.linear))
model.compile(optimizer=Adam(learning_rate=0.001),loss=MeanSquaredError(),metrics=["mse"])
model.fit(h_x_train,h_y_train,shuffle=True,batch_size=10,epochs=20,verbose=0)
score=model.evaluate(h_x_train,h_y_train,verbose=0)
print('Loss:', score[0])
print('MSE:',score[1])
pred=model.predict(h_x_test,batch_size=10)
print(pred.ravel())
print(h_y_test.ravel())

Loss: 2792375040.0
MSE: 2792375040.0
117/117 [==============================] - 1s 2ms/step
[234904.2  178038.84 155942.34 ... 177481.27 208016.17 159141.83]
[200624 133000 110000 ... 133000 222500 162500]


In [126]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train=x_train[0:6000,:]
y_train=y_train[0:6000]
x_test=x_test[0:6000,:]
y_test=y_test[0:6000]
x_train.shape

(6000, 28, 28)

In [127]:
x_train=x_train.reshape(-1, 784)
x_test=x_test.reshape(-1,784)

In [128]:
x_train=x_train.astype(np.float64)
x_test=h_x_test.astype(np.float64)
x_train/=255
x_test/=255

In [129]:
m_x_train,m_x_test,m_y_train,m_y_test=train_test_split(x_train,y_train,test_size=0.2,random_state=0)

In [130]:
enc=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
y_train_one_hot=enc.fit_transform(m_y_train[:,np.newaxis])
y_test_one_hot=enc.transform(m_y_test[:,np.newaxis])

In [131]:
model=Sequential()
model.add(Dense(50,activation=tf.nn.relu))
model.add(Dense(100,activation=tf.nn.relu))
model.add(Dense(10,activation=tf.nn.softmax))
model.compile(optimizer=Adam(learning_rate=0.001),loss=CategoricalCrossentropy(),metrics=["accuracy"])
model.fit(m_x_train,y_train_one_hot,shuffle=True,batch_size=10,epochs=300,verbose=0)
score=model.evaluate(m_x_train,y_train_one_hot,verbose=0)
print('Train loss:', score[0])
print('Train accuracy:',score[1])
pred_proba=model.predict(m_x_test,batch_size=10)
pred=np.argmax(pred_proba,1)
print(pred)

Train loss: 2.9802320611338473e-09
Train accuracy: 1.0
120/120 [==============================] - 0s 2ms/step
[9 9 4 ... 7 2 9]
